service: express-backend-boilerplate
provider:
  region: ap-southeast-1
  name: aws
  stage: prod
  runtime: nodejs16.x
functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
configValidationMode: warn
plugins:
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 8000
    noPrependStageInUrl: true
